version: "3"
services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - "3000:3000"
        volumes: 
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro 
    blogapp:
        deploy:
            replicas: 3
            restart_policy:
                condition: any
            update_config:
                parallelism: 2
                delay: 15s
                failure_action: rollback
        build: .
        environment: 
            PORT: 3000
            MONGO_USER: root
            MONGO_PASSWORD: mypass123
        command: node index.js
        depends_on: 
            - mongo
     mongodb:
        image: mongo
        volumes: 
            - mongo-storage:/data/db
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: mypass123

volumes:
    mongo-storage: